apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
# PVC with storageclass match
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  storageClassName: manual   # -> looks for the PV when storageclass is named 'manual'
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
